
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/productlabs
    username: postgres
    password: adminadmin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate: 
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
# Access H2 console at http://localhost:8080/h2-console
#  h2:
#    console.enabled: true

logging:
  level:
    root: WARN
      
wordservice:
  url:
    base: https://api.datamuse.com
    words: /words?ml=